# This file is ran separately from the rest of CI (found in ci.yaml) for two reasons.
# 1. We want to execute this codebuild job in our dev account (whereas the rest of CI currently runs in prod)
# 2. We want to enable repositories the option of whether or not these checks are added to their branch protections
version: 0.2
env:
    shell: bash
phases:
    install:
        commands:
            - python3 --version
            - python3 -m pip install --break-system-packages pre-commit
    pre_build:
        commands:
            - echo "Getting GitHub token from CodeConnections..."
            - export GITHUB_TOKEN=$(aws codeconnections get-connection-token --connection-arn arn:aws:codeconnections:us-east-1:387191992873:connection/d540a1ae-22a4-465d-a9fe-ce3f1cbd3bf6 --query 'Token' --output text)
            - git config --global credential.helper 'store'
            - echo "https://x-token:${GITHUB_TOKEN}@github.com" > ~/.git-credentials
            - export GIT_TERMINAL_PROMPT=0
            - echo "Running pre-commit hooks..."
            - pre-commit run --all-files --show-diff-on-failure
