name: Daily Scanner
  # Run Scanner processor on a daily schedule
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  daily-scanner:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Codebase
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Scanner Processor
        run: python main.py -p scanner