name: Daily Scanner
  # Run Scanner processor on a daily schedule
on:
  schedule:
    # runs every day at 4:45 UTC (23:45 EDT or 00:45 ET)
    - cron: '45 4 * * *'
jobs:
  daily-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v5
      - name: Install pipenv
        uses: pip install pipenv
      - name: Install dependencies
        run: pipenv install --dev --ignore-pipfile
      - name: Run Scanner Processor
        run: pipenv run python main.py -p scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}