on:
  # Trigger analysis when pushing changes to main branch
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]
name: QPP EU Data Publish
jobs:
  issue-create:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - CMSgov/epcs-etl
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Find changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -e '.*\.md$' -e '.*\.mermaid$' | xargs)"

      - name: Show files changed
        run: |
          echo ${{ steps.getfile.outputs.files }}

      - uses: .github/ISSUE_TEMPLATE/create_issue.md
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
