# Trigger a git issue alert on CMSgov/epcs-etl and CMSgov/qpp-eligibility repository when there is update on data folder
on:
  push:
    paths:
      - 'data/**'
    branches:
      - master
name: QPP EU Data Publish
jobs:
  gitIssueCreation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - CMSgov/epcs-etl
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Create Issue From File
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: peter-evans/create-issue-from-file@433e51abf769039ee20ba1293a088ca19d573b7f
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          title: Update EUC county zip code crosswalk mapping file
          content-filepath: .github/ISSUE_TEMPLATE/create_issue_euc_update.md
          repository: ${{ matrix.repo }}
