name: QPP EU Data Publish

on:
  release:

    types: [ published ]

jobs:

  publish-npm:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Codebase
        uses: actions/checkout@v2

      - name: Configure Node version and registry
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

# Make an announcement to other repositories of interest
  repo-dispatch:
    runs-on: ubuntu-latest
    needs: publish-npm
    strategy:
      matrix:
        repo:
          - CMSgov/epcs-etl
          - CMSgov/qpp-eligibility

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@1708dda5703a768a0fb0ef6a7a03a0c3805ebc59 #v1.1.1
        with:
          token: ${{ secrets.GH_USER_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: lib-update-event
          client-payload: '{"ref": "${{ github.ref }}", "private_package": "@CMSGov/qpp-eu-data", "public_package":"qpp-eu-data" ,"tag_name": "${{ github.event.release.tag_name }}", "html_url": "${{github.event.release.html_url}}"}'

